from pathlib import Path
import hashlib,importlib.util,json,tempfile,unittest,xml.etree.ElementTree as ET
HERE=Path(__file__).resolve().parent
REPO=next(p for p in HERE.parents if (p/'desktop/tools/extract-upstream-plugins.py').is_file())
TOOL=next(p for p in [HERE/'extract-upstream-settings-search.py',HERE.parent/'extract-upstream-settings-search.py'] if p.is_file())
spec=importlib.util.spec_from_file_location('settings_search',TOOL);e=importlib.util.module_from_spec(spec);spec.loader.exec_module(e)
class SettingsSearchExtractionTest(unittest.TestCase):
 def generate(self,standalone=True):
  root=Path(self.enterContext(tempfile.TemporaryDirectory()));files=e.generate(REPO,root,standalone)
  return root,{p.name:p.read_text(encoding='utf-8') for p in files}
 def test_original_source_identity(self):
  rows=e.inventory(REPO);self.assertEqual(14,len(rows));self.assertEqual(14,len({r['path'] for r in rows}))
  for r in rows:self.assertEqual(hashlib.sha256(e.read(REPO,r['path']).encode()).hexdigest(),r['sha256'])
 def test_pure_index_focus_and_category_are_unmodified(self):
  _,files=self.generate()
  for p in e.DIRECT:self.assertTrue(files[Path(p).name].endswith(e.read(REPO,p)))
  self.assertIn('PinyinUtils.matches(',files['SettingsSearchPolicy.kt'])
  self.assertIn('.distinctBy { it.target }',files['SettingsSearchPolicy.kt'])
 def test_direct_sync_boundary_not_duplicated(self):
  root,files=self.generate(False);self.assertEqual(8,len(files))
  for p in e.DIRECT:self.assertNotIn(Path(p).name,files)
 def test_stale_owned_direct_removed_nonowned_preserved(self):
  root,files=self.generate();self.assertEqual(15,len(files))
  e.generate(REPO,root,False)
  self.assertFalse((root/'com/android/purebilibili/feature/settings/SettingsSearchPolicy.kt').exists())
  other=root/'com/android/purebilibili/feature/settings/SettingsSearchPolicy.kt';other.write_text('not generated by this source',encoding='utf-8')
  e.generate(REPO,root,False);self.assertEqual('not generated by this source',other.read_text())
 def test_original_history_object_only_storage_imports_changed(self):
  _,files=self.generate();s=e.read(REPO,e.BASE+'core/store/SettingsSearchHistoryStore.kt')
  expected=s.replace('import android.content.Context','import com.bilipai.desktop.plugins.DesktopPluginContext as Context\nimport com.bilipai.desktop.settings.settingsSearchDataStore').replace('import androidx.datastore.preferences.core.edit\n','').replace('import androidx.datastore.preferences.core.stringPreferencesKey','import com.bilipai.desktop.plugins.stringPreferencesKey').replace('context.settingsDataStore','context.settingsSearchDataStore')
  self.assertTrue(files['SettingsSearchHistoryStore.kt'].endswith(expected))
  self.assertIn('SettingsSearchHistoryStore.record(context, query)',files['SettingsSearchHistoryOperations.kt'])
  self.assertIn('if (!privacyModeEnabled())',files['SettingsSearchHistoryOperations.kt'])
 def test_resource_identity_and_complete_original_paths(self):
  _,files=self.generate();body=files['DesktopSettingsVectors.kt'];rows=e.resource_inventory(REPO)
  self.assertEqual(182,len(rows));self.assertEqual(182,len({r['path'] for r in rows}))
  for r in rows:
   source=e.read(REPO,r['path']);self.assertEqual(hashlib.sha256(source.encode()).hexdigest(),r['sha256'])
   root=ET.fromstring(source)
   for path in root:self.assertIn(json.dumps(path.attrib[e.A+'pathData']),body)
 def test_new_xml_feature_fails_closed(self):
  from unittest.mock import patch
  old=e.read
  def changed(repo,path):return old(repo,path).replace('<path','<path android:strokeWidth="2"',1) if path.endswith('/ms_memory_24.xml') else old(repo,path)
  with patch.object(e,'read',side_effect=changed):
   with self.assertRaisesRegex(ValueError,'Unbound path attributes'):e.vectors(REPO)
 def test_active_icon_mapping_preserves_original_roles(self):
  _,files=self.generate();s=files['SettingsSemanticIconPolicy.kt']
  self.assertIn('DesktopSettingsVectors.vector(resolveSettingsMaterialSymbolResource(role))',s)
  self.assertIn('SettingsIconRole.HARDWARE_DECODER -> DesktopSettingsSymbols.ms_memory_24',s)
  self.assertNotIn('resolveMiuixSettingsSemanticIcon',s)
 def test_search_results_keep_actual_original_body(self):
  _,files=self.generate();s=files['SettingsSearchUi.kt']
  self.assertIn('results.forEachIndexed { index, result ->',s)
  self.assertIn('title = result.title',s);self.assertIn('onClick = { onResultClick(result) }',s)
  self.assertIn('rememberVectorPainter(DesktopSettingsVectors.vector(it))',s)
  self.assertNotIn('R.string',s);self.assertNotIn('R.drawable',s)
 def test_navigation_keeps_complete_original_typed_root_policy(self):
  _,files=self.generate();s=files['SettingsSearchNavigationPolicy.kt']
  self.assertIn('resolveSettingsSceneDetailFocus(result.target)',s)
  self.assertIn('else -> resolveSettingsRootCategoryForSearchTarget(result.target)',s)
  original=e.read(REPO,e.S+'SettingsSearchNavigationPolicy.kt')
  header=f"// GENERATED from {e.S}SettingsSearchNavigationPolicy.kt; do not edit.\n// LF-normalized SHA-256: {hashlib.sha256(original.encode()).hexdigest()}\n"
  self.assertEqual(header,s[:len(header)])
  self.assertEqual(original,s[len(header):])
  self.assertIn('BiliPaiNavKey.SettingsCategory(category)',s)
 def test_category_direct_target_changes_only_platform_route_types(self):
  _,files=self.generate();h=e.helper(REPO);m=h.media_extractor(REPO);parser=m.parser_for(REPO)
  original=m.function(e.read(REPO,e.S+'SettingsNavHierarchyPolicy.kt'),'resolveSettingsCategoryDirectTargetKey',parser)
  expected=original.replace('resolveSettingsCategoryDirectTargetKey','resolveDesktopSettingsCategoryDirectTarget').replace('BiliPaiNavKey?','SettingsSearchTarget?').replace('BiliPaiNavKey.AppearanceSettings','SettingsSearchTarget.APPEARANCE').replace('BiliPaiNavKey.PluginsSettings()','SettingsSearchTarget.PLUGINS')
  self.assertEqual(expected,m.function(files['DesktopSettingsRouteHierarchy.kt'],'resolveDesktopSettingsCategoryDirectTarget',parser))
  self.assertNotIn('BiliPaiNavKey',files['DesktopSettingsRouteHierarchy.kt'])
if __name__=='__main__':unittest.main()
