"""Identity, sole producers and consumer hunk audit, with no shared writes."""
from pathlib import Path
import hashlib,importlib.util,json,subprocess,sys
sys.dont_write_bytecode=True;sys.stdout.reconfigure(encoding='utf-8')
HERE=Path(__file__).resolve().parent;REPO=HERE.parents[2];CANDIDATE=REPO.parent/'BiliPai-v023'
PREFIX=chr(92)*2+'?'+chr(92)
def safe(p):
 s=str(Path(p).absolute());return Path(s if s.startswith(PREFIX) else PREFIX+s)
def read(p):return safe(p).read_text(encoding='utf-8').replace('\r\n','\n').replace('\r','\n')
def h(s):return hashlib.sha256(s.encode()).hexdigest()
def sha(p):return hashlib.sha256(safe(p).read_bytes()).hexdigest()
def write(p,s):
 p=safe(p);p.parent.mkdir(parents=True,exist_ok=True);p.write_text(s,encoding='utf-8',newline='\n')
contract=json.loads(read(HERE/'preparation-contract.json'))
registry=json.loads(read(CANDIDATE/'desktop/upstream-sources.json'))
by_path={row['path']:row for row in registry['sources']}
checks=[]
def gate(label,value):
 assert value,label;checks.append(label)
for row in contract['originalSourcePins']:
 gate('original stable LF pin: '+row['path'],h(read(CANDIDATE/row['path']))==row['sha256Lf'])
tool=HERE/'prepared/desktop/tools/extract-stable-video-votes.py'
spec=importlib.util.spec_from_file_location('vote_generator_audit',tool)
module=importlib.util.module_from_spec(spec);spec.loader.exec_module(module)
out=HERE/'audit-generated';module.generate(CANDIDATE,out)
for source in (HERE/'generated').rglob('*.kt'):
 gate('regenerated bytes equal prepared: '+source.name,sha(source)==sha(out/source.relative_to(HERE/'generated')))
gate('sole generated grade Ops fragment equals exact installed member hunk',
     read(out/'platform/DesktopVideoGradeMembers.fragment')==read(HERE/'patches/ops-grade-member.fragment.kt'))
for tail in ['feature/video/ui/components/VideoCommentVoteCard.kt','feature/video/ui/overlay/CommandDanmakuOverlayState.kt']:
 original='app/src/main/java/com/android/purebilibili/'+tail
 gate('direct original byte body is not emitted by the generator: '+tail,
      read(HERE/'direct/com/android/purebilibili'/tail)==read(CANDIDATE/original) and not (out/'com/android/purebilibili'/tail).exists())
patches=['ops-grade-member.patch','player-overlay-slot.patch','comment-vote-consumer.patch','command-owner.patch']
results=[]
for name in patches:
 p=HERE/'patches'/name
 r=subprocess.run(['git','apply','--check',str(p.absolute())],cwd=CANDIDATE,capture_output=True,text=True,encoding='utf-8')
 results.append(dict(patch=name,exitCode=r.returncode,output=r.stdout+r.stderr))
 gate('candidate current narrow patch --check: '+name,r.returncode==0)
host=read(HERE/'prepared/desktop/src/main/kotlin/com/bilipai/desktop/ui/DesktopVideoVotes.kt')
gate('native source getter + shared epoch session + CID owner getter are real guards',
 'player.currentSourceVersion == sourceVersion' in host and 'session.matches(repository, capturedEpoch)' in host and
 'danmaku.commandItemsFor(cid)' in host and 'key(alive)' in host)
gate('command state is hoisted by original session key, not remounted viewport',
 'commandState: CommandDanmakuOverlayState' in host and 'rememberCommandDanmakuOverlayState(listOf(epoch, sourceVersion, bvid, cid))' in host)
gate('no parallel HTTP/Store/account namespace',all(token not in host for token in ['OkHttpClient(', 'Retrofit.Builder(', 'DesktopPluginStore(', 'DesktopRepository(']))
gate('original ordinary vote option index and grade progress mapping retained',
 'listOf(optionIndex)' in host and 'item.startTimeMs' in host and 'option.score' in host)
gate('chapter integration kept in panel candidate', 'viewPoints = viewPoints' in read(HERE/'prepared/consumer-reference/PlayerPanels.kt'))
dm=read(HERE/'prepared/consumer-reference/DanmakuOverlay.kt')
base=read(HERE/'baseline/DanmakuOverlay.kt.reference.txt')
for anchor,end in [('    private fun installDocument(', '    private fun tick()'),('    private fun tick()', '    /** Fixture diagnostics')]:
 gate('regular renderer/scheduler unchanged: '+anchor,base[base.index(anchor):base.index(end,base.index(anchor))]==dm[dm.index(anchor):dm.index(end,dm.index(anchor))])
gate('the same command list remains the only list authority',dm.count('MutableStateFlow(emptyList<CommandDanmakuItem>())')==1 and 'private var commandCid: Long? = null' in dm)
base_path='app/src/main/java/com/android/purebilibili/'
rows=[]
for tail,mode,producer in [
 ('feature/video/ui/components/VideoCommentVoteCard.kt','direct','prepareUpstreamSources'),
 ('feature/video/ui/overlay/CommandDanmakuOverlayState.kt','direct','prepareUpstreamSources'),
 ('feature/video/ui/overlay/CommandDanmakuOverlay.kt','extracted','extract-stable-video-votes.py'),
 ('data/repository/DanmakuRepository.kt','extracted','extract-stable-video-votes.py (additional grade output, existing identity)')]:
 p=base_path+tail
 rows.append(dict(path=p,sha256=h(read(CANDIDATE/p)),mode=mode,
   features=['stable-video-vote-parity','playback','comments'],operation='merge-existing' if p in by_path else 'append-new',producer=producer))
gate('existing DanmakuRepository identity merges, without duplicate source registration',rows[-1]['operation']=='merge-existing')
references=[base_path+t for t in ['feature/video/danmaku/CommandDanmakuPolicy.kt','data/model/response/ResponseModels.kt',
 'feature/dynamic/components/DynamicVoteDialog.kt','data/repository/DynamicVoteRepository.kt','core/network/ApiClient.kt']]
gate('shared original sources are references only',all(p in by_path for p in references))
write(HERE/'source-inventory-delta.json',json.dumps(dict(upstreamTag=contract['originalTag'],upstreamCommit=contract['originalCommit'],
 actualCandidateRegistryCount=len(by_path),records=rows,referencesOnly=references,resourcesAdded=[],dependenciesAdded=[],
 compileReferencesAreNotPayload=True,sourceRegistrationMustMergeAgainstCurrentRoot=True),indent=2))
write(HERE/'audit-proof.json',json.dumps(dict(passed=True,checks=checks,patchChecks=results,
 MainChanged=False,candidateChanged=False,HWND=False,HTTP=False),indent=2))
print('Source audit PASS:',len(checks),'gates; new original identities:',sum(r['operation']=='append-new' for r in rows),'; four local hunks apply-check only.')
