from pathlib import Path
import hashlib, json, re
HERE = Path(__file__).resolve().parent
def wide(path):
    value = str(path.absolute())
    return Path(value if value.startswith('\\\\?\\') else '\\\\?\\' + value)
def sha(path): return hashlib.sha256(wide(path).read_bytes()).hexdigest()
def write(path, text):
    wide(path.parent).mkdir(parents=True, exist_ok=True)
    wide(path).write_text(text, encoding='utf-8', newline='\n')

# Production producer emits only the three selected original declarations. Tree patches and
# fixture work never run as part of a source generation task.
source = (HERE / 'prepare.py').read_text(encoding='utf-8')
source = source[:source.index("    tree_path = 'desktop/src/main/kotlin/")]
source = source.replace("HERE = Path(__file__).resolve().parent\nMAIN = HERE.parents[2]\nDEFAULT = MAIN.parent / 'BiliPai-v023'",
    "DEFAULT = Path(__file__).resolve().parents[2]")
source = source.replace('def generate(repo):', 'def generate(repo, output):')
source = source.replace("MAIN / 'desktop/tools/sync-upstream.py'", "repo / 'desktop/tools/sync-upstream.py'")
source = source.replace("MAIN / 'desktop/tools/extract-upstream-media.py'", "repo / 'desktop/tools/extract-upstream-media.py'")
source = source.replace("HERE / 'prepared/desktop/build/generated/navigation-interaction/", "output / '")
source += '''    return [dict(path=path, mode='policy-extract', features=['desktop-navigation-interaction-settings'], sha256=sha(sources[path].encode())) for path in paths]

if __name__ == '__main__':
    cli = argparse.ArgumentParser()
    cli.add_argument('--repo', type=Path, default=DEFAULT)
    cli.add_argument('--output', type=Path, required=True)
    cli.add_argument('--inventory', type=Path)
    options = cli.parse_args()
    inventory = generate(options.repo, options.output)
    if options.inventory:
        write(options.inventory, json.dumps(inventory, ensure_ascii=False, indent=2) + '\\n')
'''
write(HERE / 'prepared/desktop/tools/extract-upstream-navigation-interaction.py', source)
test = (HERE / 'NavigationSettingsFixture.kt').read_text(encoding='utf-8')
test = test[:test.index('\nfun main(): Unit')].replace('class NavigationSettingsFixture', 'class DesktopNavigationInteractionSettingsTest')
write(HERE / 'prepared/desktop/src/test/kotlin/com/bilipai/desktop/settings/DesktopNavigationInteractionSettingsTest.kt', test)
base = json.loads((HERE / 'base-identity.json').read_text())
targets = []
for path in sorted(wide(HERE / 'prepared').rglob('*')):
    if not path.is_file(): continue
    relative = path.relative_to(wide(HERE / 'prepared')).as_posix()
    # Build outputs are verification templates, generated by the new exact producer at integration.
    kind = 'generated-template' if '/build/generated/' in relative else 'production-target'
    targets.append(dict(target=relative, preparedPath=str(path), kind=kind, sha256Bytes=sha(path),
        expectedBaseSha256Bytes=base['treeBaseSha256Bytes'] if relative.endswith('/DesktopSettingsTree.kt') else None))
result = json.loads((HERE / 'runs/05/result.json').read_text())
ui = json.loads((HERE / 'runs/05/ui/result.json').read_text())
contract = dict(frozen=True, slice='seven-original-navigation-card-motion-controls', upstreamTag='v0.2.3',
    upstreamCommit='3d5d19a2f994daccd0e2f8b5f522b6d82f43d589', candidateProductionUntouched=True,
    actualSnapshotManifestSha256Bytes=result['actualSnapshotManifestSha256Bytes'], targets=targets,
    sourceInventory='source-inventory.json', productionOverrides=result['declaredProductOverrides'],
    evidence='runs/05/result.json', evidenceSha256Bytes=sha(HERE / 'runs/05/result.json'),
    uiEvidence='runs/05/ui/result.json', uiEvidenceSha256Bytes=sha(HERE / 'runs/05/ui/result.json'),
    focusedExecutableMethods=6, uiCases=len(ui['cases']), actualPointerCount=sum(c['pointerCount'] for c in ui['cases']),
    fullBottomBarAnimationComplete=False, wholeMainRuntimeAccepted=False,
    categoryAuditCorrection='Appearance and Plugins already route directly through existing generated helper; no mutation of their admission.',
    remaining=['bottom/top navigation order and visibility editing','search-tab order','navigation label/color customization',
        'sidebar/tablet preferences UI','all other animation/blur/gesture/haptic settings','actual on-screen Root animation and chrome acceptance'])
write(HERE / 'frozen-handoff.json', json.dumps(contract, ensure_ascii=False, indent=2) + '\n')
files = []
for path in sorted(wide(HERE).rglob('*')):
    if not path.is_file() or path.name == 'freeze-manifest.json' or '/__pycache__/' in str(path).replace('\\','/') or '/runs/01/' in str(path).replace('\\','/') or '/runs/02/' in str(path).replace('\\','/') or '/runs/04/' in str(path).replace('\\','/'): continue
    files.append(dict(path=path.relative_to(wide(HERE)).as_posix(), sha256Bytes=sha(path)))
write(HERE / 'freeze-manifest.json', json.dumps(dict(frozen=True, files=files, handoffSha256Bytes=sha(HERE/'frozen-handoff.json')), indent=2) + '\n')
print(json.dumps(dict(handoffSha256Bytes=sha(HERE/'frozen-handoff.json'), files=len(files), productionTargets=sum(t['kind']=='production-target' for t in targets), generatedTemplates=sum(t['kind']=='generated-template' for t in targets), pointerCount=contract['actualPointerCount'])))
