"""After Root's normal producer runs, check actual generated bytes and one DIRECT owner."""
from pathlib import Path
import argparse,hashlib,json,os,sys
sys.stdout.reconfigure(encoding='utf8')
P=Path(__file__).resolve().parent;M=P.parents[2]
parser=argparse.ArgumentParser();parser.add_argument('--candidate',type=Path,default=M.parent/'BiliPai-v023');parser.add_argument('--contract',type=Path,default=P/'root-install-contract.json');args=parser.parse_args()
def wide(p):
 s=str(p);return Path(s if s.startswith('\\\\?\\')else'\\\\?\\'+os.path.abspath(s))
def raw(p):return wide(p).read_bytes()
def digest(b):return hashlib.sha256(b).hexdigest()
contract=json.loads(raw(args.contract));F=Path(contract['frozenPacket']);packet=json.loads(raw(F/'install-contract.json'))
assert digest(raw(F/'install-contract.json'))==contract['frozenContractSha256']
inventory=json.loads(raw(F/'source-inventory.json'));direct={Path(r['path']).name:r for r in inventory if r['mode']=='direct'}
root=args.candidate/'desktop/build/generated/original-message-pages';verified=[]
for row in packet['generatedFiles']:
 relative=Path(row['path']).relative_to('generated');name=relative.name
 if name in direct:
  source=direct[name];path=args.candidate/'desktop/build/generated/upstream'/source['path']
  assert digest(raw(path).replace(b'\r\n',b'\n'))==source['sha256']
  assert not wide(root/relative).exists(),'DIRECT unexpectedly generated twice'
  verified.append(dict(path=str(path),owner='prepareUpstreamSources',normalization='lf',sha256=source['sha256']))
 else:
  path=root/relative;assert digest(raw(path))==row['sha256Bytes'],str(path)
  verified.append(dict(path=str(path),owner='extractOriginalMessagePages',normalization='raw',sha256=row['sha256Bytes']))
assert len(list(wide(root).rglob('*.kt')))==13
print(json.dumps(dict(passed=True,directSoleProducerFiles=4,exactGeneratedFiles=13,verified=verified,rootRuntimeAccepted=False),ensure_ascii=False,indent=2))
