from pathlib import Path
import hashlib,json
P=Path(__file__).resolve().parent;MAIN=P.parents[2];REPO=MAIN.parent/'BiliPai-v023';SNAP=MAIN/'desktop/.local/stable-product-snapshot-68'
def wide(p):
 s=str(Path(p).absolute());return Path(s if s.startswith('\\\\?\\')else'\\\\?\\'+s)
def read(p):return wide(p).read_bytes()
def sha(p):return hashlib.sha256(read(p)).hexdigest()
def save(p,v):wide(p).parent.mkdir(parents=True,exist_ok=True);wide(p).write_bytes((json.dumps(v,ensure_ascii=False,indent=2)+'\n').encode())
result=json.loads(read(P/'runs/01/result.json'));assert result['passed'] and result['assertions']==33 and result['productionOverrides']==0
snap=json.loads(read(SNAP/'manifest.json'));src='desktop/src/main/kotlin/com/bilipai/desktop/plugins/DesktopPluginRuntime.kt'
actual=next(r for r in snap['inputs']if r['path']==src);assert sha(REPO/src)==actual['sha256Bytes']
wide(P/'source-review').mkdir(exist_ok=True);wide(P/'source-review/DesktopPluginRuntime.kt').write_bytes(read(REPO/src))
review=dict(passed=True,scope='Independent source review plus focused actual68 memory fixture; no Native/Root authority acceptance',source=dict(path=src,sha256Bytes=actual['sha256Bytes']),actualSnapshotManifestSHA256=sha(SNAP/'manifest.json'),findings=[dict(status='confirmed',anchor='DesktopPluginRuntime.kt:283–305',claim='Dispatch captures exact CurrentVideo object and Runtime identity, generation/BVID/CID, owner predicate and enabled provider identities; every operation rejects a foreign token and stale/disabled provider.'),dict(status='confirmed',anchor='DesktopPluginRuntime.kt:308–321',claim='Mutex waiting is outside admission; synchronous mutation runs within short captured-source admission and caller cancellation/dispatch are rechecked before its result is returned.'),dict(status='confirmed',anchor='DesktopPluginRuntime.kt:325–337',claim='Suspending provider callback work runs outside admission, with pre/post short admission and caller/identity/provider rechecks. Rejection does not claim to undo an already admitted in-flight side effect.'),dict(status='confirmed',anchor='DesktopPluginRuntime.kt:342–363',claim='Retirement captures old provider identities and uses existing Runtime scope, not canceled VM scope. Old-generation cleanup cannot reset a subsequent load whose generation increments before waiting for playerMutex.'),dict(status='confirmed',anchor='DesktopPluginRuntime.kt:444–472',claim='Real Runtime shutdown canceled/joined its jobs, JS/subscription/package lifecycle and actual registered plugin scopes; same Store rejects subsequent writes.')],fixtureBoundaries=['MemoryNativeLease is an explicit fixture-owned predicate/short admission, not a Store/account/native lease proof','FixturePlayerPlugin delayed callbacks and counters are test doubles registered through actual PluginManager; all production PlayerPlugin providers including Sponsor are disabled','Second Runtime exists only to verify rejection of a foreign token; it uses the same temporary Store/GlobalPluginManager and both real shutdownForRestore joins. This does not support a second production Runtime authority','Actual JS catalog compiled into main68 and every existing resource file were verified; no fake catalog, new runtime download or JS plugin execution','No product classes recompiled/overridden; actual4 class origins/bytes and all101CP pre/post hashes verified','No HTTP, account, GUI/HWND/input/native operation performed'],pending=['NativeOwner/whole Root assembly','Original legacy CDN delayed-write guard','Original history final-write admission'])
save(P/'source-review/review.json',review)
paths=[P/'RuntimeDispatchFixture.kt',P/'run.py',P/'freeze.py',P/'worker-resource-identity.json',P/'source-review/review.json',P/'source-review/DesktopPluginRuntime.kt']
paths += [P/'runs/01'/n for n in ['RuntimeDispatchFixture.kt','compile.args','compile.log','compile-result.json','run-command.json','run.log','pins-before.json','pins-after.json','class-overlap.json','actual-code-origins.json','result.json','runtime/result.json']]
rows=[dict(path=p.relative_to(P).as_posix(),sha256Bytes=sha(p),bytes=len(read(p)))for p in paths]
manifest=dict(frozen=True,phase='actual68-zero-production-override-runtime-dispatch-memory-proof',passed=True,assertions=33,actualSnapshot=dict(manifestPath=str(SNAP/'manifest.json'),manifestSHA256=sha(SNAP/'manifest.json'),orderedCPPath=str(SNAP/'ordered-runtime-cp.json'),orderedCPSHA256=sha(SNAP/'ordered-runtime-cp.json'),entries=101,mainKotlinSHA256='bb2fb5cd152d53afc4bcaaca150677773f011b2dd74fe980ef64f6d1caa75280'),actualLoadedProductClasses=4,productionOverrides=0,fixtureClassIntersectionZero=True,allRuntimeAndWorkerResourcesPrePostVerified=True,realRuntimeShutdownJoins=True,secondRuntimeOnlyForeignTokenFixture=True,nativeLeaseAndProviderExplicitTestDoubles=True,httpAccountGuiOrNativeRun=False,fullRootOrNativeAccepted=False,sourceReview='source-review/review.json',result='runs/01/result.json',artifacts=rows,rawArtifactCount=len(rows),excluded=['runs/01/fixture.jar','*.class','runs/01/runtime/private-store/**','actual production and worker JAR/runtime binaries (referenced by verified pins only)'],pending=review['pending'])
save(P/'frozen-proof.json',manifest)
print(json.dumps(dict(path=str(P/'frozen-proof.json'),sha256Bytes=sha(P/'frozen-proof.json'),rows=len(rows),resultPath=str(P/'runs/01/result.json'),resultSHA256Bytes=sha(P/'runs/01/result.json'))))
